title: NotesPrep
description: Free Study Notes, MCQs & Entry Test Preparation for FBISE, NUST, and MDCAT.
url: "https://notesprep.com"
twitter:
  username: notesprep  # Replace with your actual username
logo: /assets/img/logo.png

# This tells the plugin what image to use if a page doesn't have one
image: https://notesprep.com/drawing.png
url: "https://notesprep.com" 
baseurl: ""  # Keep empty for custom domain
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Important for your existing files
keep_files:
  - assets  # This preserves your existing files